---
name: 'ServiceNow Authentication'
description: >-
  Prepares ServiceNow authentication credentials for both official actions and
  curl-based API calls
author: 'Microservices Demo Team'

outputs:
  username:
    description: 'ServiceNow username (from secrets)'
    value: ${{ steps.auth.outputs.username }}
  password:
    description: 'ServiceNow password (from secrets)'
    value: ${{ steps.auth.outputs.password }}
  instance-url:
    description: 'ServiceNow instance URL (from secrets)'
    value: ${{ steps.auth.outputs.instance_url }}
  tool-id:
    description: 'ServiceNow orchestration tool ID (from secrets)'
    value: ${{ steps.auth.outputs.tool_id }}
  basic-auth:
    description: 'Base64-encoded Basic Auth header for curl (username:password)'
    value: ${{ steps.auth.outputs.basic_auth }}

runs:
  using: 'composite'
  steps:
    - name: Prepare ServiceNow Authentication
      id: auth
      run: |
        # Pass through credentials from environment
        echo "username=$SERVICENOW_USERNAME" >> $GITHUB_OUTPUT
        echo "password=$SERVICENOW_PASSWORD" >> $GITHUB_OUTPUT
        echo "instance_url=$SERVICENOW_INSTANCE_URL" >> $GITHUB_OUTPUT
        echo "tool_id=$SN_ORCHESTRATION_TOOL_ID" >> $GITHUB_OUTPUT

        # Generate Base64-encoded Basic Auth for curl commands
        BASIC_AUTH=$(echo -n "$SERVICENOW_USERNAME:$SERVICENOW_PASSWORD" | base64)
        echo "basic_auth=$BASIC_AUTH" >> $GITHUB_OUTPUT

        echo "✅ ServiceNow authentication prepared"
      shell: bash
      env:
        SERVICENOW_USERNAME: ${{ env.SERVICENOW_USERNAME }}
        SERVICENOW_PASSWORD: ${{ env.SERVICENOW_PASSWORD }}
        SERVICENOW_INSTANCE_URL: ${{ env.SERVICENOW_INSTANCE_URL }}
        SN_ORCHESTRATION_TOOL_ID: ${{ env.SN_ORCHESTRATION_TOOL_ID }}
