name: Terraform Validation and Testing

on:
  pull_request:
    paths:
      - 'terraform-aws/**'
      - '.github/workflows/terraform-validate.yaml'
  push:
    branches:
      - main
    paths:
      - 'terraform-aws/**'
  workflow_dispatch:

env:
  TERRAFORM_VERSION: '1.5.0'
  AWS_REGION: 'eu-west-2'

jobs:
  terraform-fmt:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        working-directory: terraform-aws
        run: |
          terraform fmt -check -recursive
          if [ $? -ne 0 ]; then
            echo "❌ Terraform files are not properly formatted"
            echo "Run 'terraform fmt -recursive' to fix"
            exit 1
          fi
          echo "✅ All Terraform files are properly formatted"

  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        working-directory: terraform-aws
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform-aws
        run: |
          terraform validate
          echo "✅ Terraform configuration is valid for ${{ matrix.environment }}"

  terraform-lint:
    name: TFLint Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Initialize TFLint
        working-directory: terraform-aws
        run: tflint --init

      - name: Run TFLint
        working-directory: terraform-aws
        run: |
          tflint --format=compact --recursive
          echo "✅ TFLint checks passed"

  terraform-security:
    name: Security Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform-aws
          framework: terraform
          output_format: cli,sarif
          output_file_path: console,checkov-results.sarif
          soft_fail: true

      - name: Upload Checkov results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif
          category: checkov

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform-aws
          format: sarif
          soft_fail: true
          sarif_file: tfsec-results.sarif

      - name: Upload tfsec results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec-results.sarif
          category: tfsec
        continue-on-error: true

      - name: Run Trivy for IaC scanning
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'terraform-aws'
          format: 'sarif'
          output: 'trivy-iac-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
        continue-on-error: true

      - name: Upload Trivy results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-iac-results.sarif
          category: trivy-iac
        continue-on-error: true

  terraform-cost:
    name: Cost Estimation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform-aws
        run: terraform init

      - name: Generate Terraform Plan
        working-directory: terraform-aws
        run: |
          terraform plan -out=plan.tfplan

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        working-directory: terraform-aws
        run: |
          infracost breakdown \
            --path=plan.tfplan \
            --format=json \
            --out-file=infracost.json || echo "Infracost analysis failed (optional)"

      - name: Post Infracost comment
        if: github.event_name == 'pull_request'
        uses: infracost/actions/comment@v1
        with:
          path: terraform-aws/infracost.json
          behavior: update

  terraform-docs:
    name: Documentation Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform-docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: terraform-aws
          output-file: README-GENERATED.md
          output-method: inject
          git-push: false

      - name: Check if documentation is up to date
        working-directory: terraform-aws
        run: |
          if [ -f README-GENERATED.md ]; then
            echo "✅ Terraform documentation generated successfully"
          else
            echo "❌ Failed to generate Terraform documentation"
            exit 1
          fi

  terraform-test:
    name: Terraform Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform-aws
        run: terraform init

      - name: Run Terraform Tests
        working-directory: terraform-aws
        run: |
          if [ -d "tests" ]; then
            terraform test
            echo "✅ All Terraform tests passed for ${{ matrix.environment }}"
          else
            echo "ℹ️ No Terraform tests found (tests/ directory doesn't exist)"
          fi

  summary:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [terraform-fmt, terraform-validate, terraform-lint, terraform-security, terraform-test]
    if: always()
    steps:
      - name: Check job results
        run: |
          if [ "${{ needs.terraform-fmt.result }}" != "success" ] || \
             [ "${{ needs.terraform-validate.result }}" != "success" ] || \
             [ "${{ needs.terraform-lint.result }}" != "success" ]; then
            echo "❌ Some validation checks failed"
            exit 1
          fi
          echo "✅ All validation checks passed successfully"

      - name: Post summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const summary = `### Terraform Validation Results 🎯

            | Check | Status |
            |-------|--------|
            | Format | ${{ needs.terraform-fmt.result == 'success' && '✅' || '❌' }} |
            | Validation | ${{ needs.terraform-validate.result == 'success' && '✅' || '❌' }} |
            | Linting | ${{ needs.terraform-lint.result == 'success' && '✅' || '❌' }} |
            | Security | ${{ needs.terraform-security.result == 'success' && '✅' || '❌' }} |
            | Tests | ${{ needs.terraform-test.result == 'success' && '✅' || '❌' }} |

            All environments (dev, qa, prod) have been validated.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
