#!/usr/bin/env bash

# Copyright 2024
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script compiles manifest files with the image tags and places them in
# /release/...

set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT=$SCRIPT_DIR/../..
[[ -n "${DEBUG:-}" ]] && set -x

log() { echo "$1" >&2; }

TAG="${TAG:?TAG env variable must be specified}"
AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:?AWS_ACCOUNT_ID env variable must be specified}"
AWS_REGION="${AWS_REGION:-eu-west-2}"
REPO_PREFIX="${REPO_PREFIX:-$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com}"
OUT_DIR="${OUT_DIR:-${REPO_ROOT}/release}"

print_license_header() {
    cat "${SCRIPT_DIR}/license_header.txt"
    echo
}

print_autogenerated_warning() {
    cat<<EOF
# ----------------------------------------------------------
# WARNING: This file is autogenerated. Do not manually edit.
# ----------------------------------------------------------

EOF
}

# Use gsed if available (macOS with gnu-sed), otherwise use sed (Linux)
if command -v gsed >/dev/null 2>&1; then
    SED_CMD="gsed"
else
    SED_CMD="sed"
fi

read_manifests_except_kustomization() {
    local dir
    dir="$1"

    while IFS= read -d $'\0' -r file; do
        echo "---"

        # strip license headers (pattern "^# ")
        awk '
        /^[^# ]/ { found = 1 }
        found { print }' "${file}"
    done < <(find "${dir}" -name '*.yaml' ! -name 'kustomization.yaml' -type f -print0)
}

mk_kubernetes_manifests() {
    out_manifest="$(read_manifests_except_kustomization "${REPO_ROOT}/kubernetes-manifests")"

    # replace "image" repo, tag for each service
    for dir in ./src/*/
    do
        svcname="$(basename "${dir}")"
        image="$REPO_PREFIX/$svcname:$TAG"

        pattern="^(\s*)image:\s.*$svcname(.*)(\s*)"
        replace="\1image: $image\3"
        out_manifest="$($SED_CMD -r "s|$pattern|$replace|g" <(echo "${out_manifest}") )"
    done

    print_license_header
    print_autogenerated_warning
    echo '# [START eks_release_kubernetes_manifests_microservices_demo]'
    echo "${out_manifest}"
    echo "# [END eks_release_kubernetes_manifests_microservices_demo]"
}

mk_istio_manifests() {
    print_license_header
    print_autogenerated_warning
    echo '# [START istio_release_istio_manifests_microservices_demo]'

    # Copy the istio manifests
    read_manifests_except_kustomization "${REPO_ROOT}/istio-manifests/"
    echo '# [END istio_release_istio_manifests_microservices_demo]'
}

mk_kustomize_base() {
  for file_to_copy in ./kubernetes-manifests/*.yaml
  do
    # Don't copy kustomization.yaml.
    if [[ $file_to_copy == "./kubernetes-manifests/kustomization.yaml" ]]; then
      continue
    fi

    cp ${file_to_copy} ./kustomize/base/

    service_name="$(basename "${file_to_copy}" .yaml)"
    image="$REPO_PREFIX/$service_name:$TAG"

    # Inside redis.yaml, we use the official `redis:alpine` Docker image.
    # We don't use an image from ECR for redis.
    if [[ $service_name == "redis" ]]; then
      continue
    fi

    pattern="^(\s*)image:\s.*${service_name}(.*)(\s*)"
    replace="\1image: ${image}\3"
    $SED_CMD --in-place --regexp-extended "s|${pattern}|${replace}|g" ./kustomize/base/${service_name}.yaml
  done
}

main() {
    mkdir -p "${OUT_DIR}"
    local k8s_manifests_file istio_manifests_file

    k8s_manifests_file="${OUT_DIR}/kubernetes-manifests.yaml"
    mk_kubernetes_manifests > "${k8s_manifests_file}"
    log "Written ${k8s_manifests_file}"

    istio_manifests_file="${OUT_DIR}/istio-manifests.yaml"
    mk_istio_manifests > "${istio_manifests_file}"
    log "Written ${istio_manifests_file}"

    mk_kustomize_base
    log "Written Kustomize base"
}

main
