#!/usr/bin/env bash
# Automated version promotion workflow
# Creates PR → Merges → Deploys dev → qa → prod
#
# Usage:
#   ./scripts/promote-version.sh 1.1.8 all
#   ./scripts/promote-version.sh 1.1.9 frontend,cartservice

set -euo pipefail

VERSION="${1:-}"
SERVICES="${2:-all}"  # "all" or specific service names

if [ -z "$VERSION" ]; then
    echo "Usage: $0 <version> [services]"
    echo ""
    echo "Examples:"
    echo "  $0 1.1.8 all                    # Promote all services"
    echo "  $0 1.1.9 frontend,cartservice   # Promote specific services"
    echo ""
    exit 1
fi

echo "🚀 Starting Automated Version Promotion"
echo "========================================"
echo "Version: $VERSION"
echo "Services: $SERVICES"
echo ""

# Set default repository for gh CLI if not already set
REPO_OWNER=$(git remote get-url origin | sed -n 's#.*/\([^/]*\)/\([^/]*\)\.git#\1#p' || echo "")
REPO_NAME=$(git remote get-url origin | sed -n 's#.*/\([^/]*\)/\([^/]*\)\.git#\2#p' || echo "")
if [ -n "$REPO_OWNER" ] && [ -n "$REPO_NAME" ]; then
    gh repo set-default "$REPO_OWNER/$REPO_NAME" 2>/dev/null || true
fi

# Ensure we're on main and up to date
echo "📥 Ensuring main branch is up to date..."
git checkout main 2>/dev/null || true
git fetch origin main
git reset --hard origin/main

# 1. Create feature branch
BRANCH="release/v${VERSION}"
echo "📝 Creating feature branch: $BRANCH"

# Delete branch if it exists
git branch -D "$BRANCH" 2>/dev/null || true
git push origin --delete "$BRANCH" 2>/dev/null || true

git checkout -b "$BRANCH"

# 2. Update kustomization files for all environments with semantic version
echo "📝 Updating kustomization files..."
for ENV in dev qa prod; do
    FILE="kustomize/overlays/$ENV/kustomization.yaml"
    if [ -f "$FILE" ]; then
        echo "  - $FILE"
        # Update to semantic version tag (v1.2.0)
        # Images will be tagged with this version during build
        sed -i "s/newTag: .*/newTag: v${VERSION}/" "$FILE"
        git add "$FILE"
    fi
done

# 3. Commit changes
echo "✅ Committing version update"

# Check if there are any changes to commit
if git diff --cached --quiet; then
    echo "⚠️  No changes detected - version already at v${VERSION}"
    echo ""
    echo "All kustomization files are already using v${VERSION}."
    echo "Nothing to do. Exiting successfully."

    # Clean up branch
    git checkout main 2>/dev/null || true
    git branch -D "$BRANCH" 2>/dev/null || true

    exit 0
fi

git commit -m "chore: Promote to version ${VERSION}

Automated version promotion via scripts/promote-version.sh

- Version: ${VERSION}
- Services: ${SERVICES}
- Environments: dev, qa, prod
- Tags: v${VERSION} (semantic versioning)

This PR will trigger:
1. Auto-deploy to DEV (ServiceNow CR auto-approved)
2. Manual deploy to QA (requires ServiceNow approval)
3. Manual deploy to PROD (requires ServiceNow approval)
"

# 4. Push branch
echo "⬆️  Pushing branch to origin"
git push origin "$BRANCH"

# 5. Create Pull Request
echo "📝 Creating Pull Request"

# Check if PR already exists for this branch
echo "   Checking for existing PR for branch: $BRANCH"
EXISTING_PR=$(gh pr list --head "$BRANCH" --json number,url --jq '.[0].url' 2>/dev/null || echo "")

if [ -n "$EXISTING_PR" ]; then
    echo "ℹ️  PR already exists for branch $BRANCH: $EXISTING_PR"
    PR_URL="$EXISTING_PR"
else
    echo "   Creating new PR..."
    # Create new PR using simpler approach
    # gh pr create outputs URL to stdout on success, error message to stderr on failure
    set +e  # Don't exit on error
    PR_OUTPUT=$(gh pr create \
        --base main \
        --head "$BRANCH" \
        --title "Release v${VERSION}" \
        --body "## 🚀 Automated Version Promotion

**Version**: ${VERSION}
**Services**: ${SERVICES}

## 📋 Changes

This PR updates kustomization files for all environments to use semantic version tag.

- ✅ Dev environment: \`newTag: v${VERSION}\`
- ✅ QA environment: \`newTag: v${VERSION}\`
- ✅ Prod environment: \`newTag: v${VERSION}\`

## 🔄 Deployment Plan

1. **DEV** - Auto-deploy on merge (ServiceNow CR auto-approved)
2. **QA** - Manual trigger required (ServiceNow CR requires approval)
3. **PROD** - Manual trigger required (ServiceNow CR requires approval)

## ✅ Verification Checklist

- [ ] All services built successfully
- [ ] DEV deployment healthy
- [ ] QA deployment healthy
- [ ] PROD deployment healthy
- [ ] ServiceNow change requests created
- [ ] GitHub release created

## 📝 ServiceNow Integration

Each environment will automatically create a ServiceNow Change Request:
- **DEV**: Auto-approved (state = \"implement\")
- **QA**: Requires manual approval (state = \"assess\")
- **PROD**: Requires manual approval (state = \"assess\")

All test results, packages, and configs will be uploaded to ServiceNow.

---

🤖 Generated by scripts/promote-version.sh
" 2>&1)

    PR_EXIT_CODE=$?
    set -e  # Re-enable exit on error

    # Check if PR creation failed
    if [ $PR_EXIT_CODE -ne 0 ]; then
        echo "❌ Failed to create PR (exit code: $PR_EXIT_CODE)"
        echo ""
        echo "Error output:"
        echo "$PR_OUTPUT"
        echo ""
        echo "This might happen if:"
        echo "  - GitHub API rate limit exceeded"
        echo "  - Network connectivity issues"
        echo "  - Insufficient permissions"
        echo "  - Branch protection rules prevent PR creation"
        echo ""
        echo "You can create the PR manually:"
        echo "  gh pr create --base main --head $BRANCH --title 'Release v${VERSION}' --fill"
        exit 1
    fi

    PR_URL="$PR_OUTPUT"
fi

# Validate PR URL
if [ -z "$PR_URL" ] || [[ ! "$PR_URL" =~ ^https://github.com/ ]]; then
    echo "❌ Failed to get valid PR URL: '$PR_URL'"
    echo ""
    echo "You can create the PR manually:"
    echo "  gh pr create --base main --head $BRANCH --title 'Release v${VERSION}' --fill"
    exit 1
fi

echo "✅ Pull Request created: $PR_URL"
echo ""

# 6. Wait for CI checks to pass
echo "⏳ Waiting for CI checks to pass..."
sleep 10  # Give GitHub time to register the PR and start CI

# Get PR number from URL
PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')

# Watch CI checks
gh pr checks "$PR_NUMBER" --watch || {
    echo "❌ CI checks failed. Please review the PR: $PR_URL"
    echo ""
    echo "You can continue manually:"
    echo "  1. Fix issues and push to $BRANCH"
    echo "  2. Wait for CI to pass"
    echo "  3. Approve and merge PR: gh pr merge $PR_NUMBER --squash --delete-branch"
    exit 1
}

echo ""
echo "✅ CI checks passed!"
echo ""

# 7. Wait for manual approval before merging
echo "📋 Review PR: $PR_URL"
echo ""
read -p "✅ Merge PR and proceed with deployment? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "⏸️  Merge cancelled. You can merge manually later:"
    echo "   gh pr merge $PR_NUMBER --squash --delete-branch"
    exit 0
fi

# 8. Merge PR
echo "✅ Merging PR..."
gh pr merge "$PR_NUMBER" --squash --delete-branch --body "✅ Manual merge confirmation - CI checks passed

All validations complete:
- ✅ Security scans passed
- ✅ Code validation passed
- ✅ Kustomize configurations valid

Merged via scripts/promote-version.sh" || {
    echo "❌ Failed to merge PR. Please merge manually: $PR_URL"
    echo ""
    echo "This might happen if:"
    echo "  - Branch protection rules require approval"
    echo "  - GitHub doesn't allow merging your own PR"
    echo ""
    echo "To merge manually:"
    echo "  gh pr merge $PR_NUMBER --squash --delete-branch"
    exit 1
}

echo "✅ PR merged to main"
echo ""

# 8. Wait for main branch to be updated
echo "⏳ Waiting for main branch update..."
git checkout main
git pull origin main
sleep 5  # Give GitHub Actions time to start

echo ""

# 9. Trigger MASTER-PIPELINE for DEV with force build
echo "🟢 Triggering DEV deployment (with force build)..."
echo "   ServiceNow CR: Auto-approved for dev"
echo "   Version: $VERSION"
echo ""

gh workflow run MASTER-PIPELINE.yaml -f environment=dev -f force_build_all=true -f version=$VERSION

sleep 15  # Let workflow start

# Get the latest MASTER-PIPELINE run
DEV_RUN=$(gh run list --workflow=MASTER-PIPELINE.yaml --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || echo "")

if [ -n "$DEV_RUN" ]; then
    echo "   📊 Workflow run: https://github.com/$(gh repo view --json nameWithOwner --jq '.nameWithOwner')/actions/runs/$DEV_RUN"
    echo "   ⏳ Watching workflow progress..."
    echo ""

    gh run watch "$DEV_RUN" --exit-status || {
        echo "❌ DEV deployment failed. Check workflow: https://github.com/$(gh repo view --json nameWithOwner --jq '.nameWithOwner')/actions/runs/$DEV_RUN"
        exit 1
    }

    echo ""
    echo "✅ DEV deployment complete"
else
    echo "⚠️  Could not find workflow run. Check manually:"
    echo "   https://github.com/$(gh repo view --json nameWithOwner --jq '.nameWithOwner')/actions"
fi

echo ""

# 10. Prompt for QA deployment
read -p "🟡 Deploy to QA? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🟡 Triggering QA deployment (with force build)..."
    echo "   ServiceNow CR: Requires manual approval in ServiceNow"
    echo "   Version: $VERSION"
    echo ""

    gh workflow run MASTER-PIPELINE.yaml -f environment=qa -f force_build_all=true -f version=$VERSION

    sleep 10  # Let workflow start

    QA_RUN=$(gh run list --workflow=MASTER-PIPELINE.yaml --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || echo "")

    if [ -n "$QA_RUN" ]; then
        echo "   📊 Workflow run: https://github.com/$(gh repo view --json nameWithOwner --jq '.nameWithOwner')/actions/runs/$QA_RUN"
        echo "   ⏸️  Waiting for ServiceNow CR approval..."
        echo "   📝 Approve at: https://calitiiltddemo3.service-now.com/now/nav/ui/classic/params/target/change_request_list.do"
        echo ""

        gh run watch "$QA_RUN" --exit-status || {
            echo "❌ QA deployment failed. Check workflow: https://github.com/$(gh repo view --json nameWithOwner --jq '.nameWithOwner')/actions/runs/$QA_RUN"
            exit 1
        }

        echo ""
        echo "✅ QA deployment complete"
    else
        echo "⚠️  Could not find workflow run. Check manually:"
        echo "   https://github.com/$(gh repo view --json nameWithOwner --jq '.nameWithOwner')/actions"
    fi

    echo ""
fi

# 11. Prompt for PROD deployment
read -p "🔴 Deploy to PROD? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🔴 Triggering PROD deployment (with force build)..."
    echo "   ServiceNow CR: Requires manual approval in ServiceNow"
    echo "   Version: $VERSION"
    echo ""

    gh workflow run MASTER-PIPELINE.yaml -f environment=prod -f force_build_all=true -f version=$VERSION

    sleep 10  # Let workflow start

    PROD_RUN=$(gh run list --workflow=MASTER-PIPELINE.yaml --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || echo "")

    if [ -n "$PROD_RUN" ]; then
        echo "   📊 Workflow run: https://github.com/$(gh repo view --json nameWithOwner --jq '.nameWithOwner')/actions/runs/$PROD_RUN"
        echo "   ⏸️  Waiting for ServiceNow CR approval..."
        echo "   📝 Approve at: https://calitiiltddemo3.service-now.com/now/nav/ui/classic/params/target/change_request_list.do"
        echo ""

        gh run watch "$PROD_RUN" --exit-status || {
            echo "❌ PROD deployment failed. Check workflow: https://github.com/$(gh repo view --json nameWithOwner --jq '.nameWithOwner')/actions/runs/$PROD_RUN"
            exit 1
        }

        echo ""
        echo "✅ PROD deployment complete"
    else
        echo "⚠️  Could not find workflow run. Check manually:"
        echo "   https://github.com/$(gh repo view --json nameWithOwner --jq '.nameWithOwner')/actions"
    fi

    echo ""
fi

echo "🎉 Version promotion complete!"
echo "================================"
echo ""
echo "## 📊 Summary"
echo ""
echo "| Item | Value |"
echo "|------|-------|"
echo "| Version | **${VERSION}** |"
echo "| Services | ${SERVICES} |"
echo "| Branch | \`$BRANCH\` (merged and deleted) |"
echo "| PR | $PR_URL |"
echo ""
echo "### 🌍 Environments"
echo ""
echo "- ✅ **DEV** - Deployed"
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "- ✅ **QA** - Deployed"
    echo "- ✅ **PROD** - Deployed"
else
    echo "- ⏭️ **QA** - Skipped"
    echo "- ⏭️ **PROD** - Skipped"
fi
echo ""
echo "### 📝 Next Steps"
echo ""
echo "1. Verify deployments in Kubernetes:"
echo "   \`\`\`bash"
echo "   kubectl get pods -n microservices-dev"
echo "   kubectl get pods -n microservices-qa"
echo "   kubectl get pods -n microservices-prod"
echo "   \`\`\`"
echo ""
echo "2. Check ServiceNow Change Requests:"
echo "   https://calitiiltddemo3.service-now.com/now/nav/ui/classic/params/target/change_request_list.do"
echo ""
echo "3. View frontend applications:"
DEV_URL=$(kubectl get ingress frontend-ingress -n microservices-dev -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "Not deployed yet")
QA_URL=$(kubectl get ingress frontend-ingress -n microservices-qa -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "Not deployed yet")
PROD_URL=$(kubectl get ingress frontend-ingress -n microservices-prod -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "Not deployed yet")
echo "   - DEV: http://$DEV_URL"
echo "   - QA: http://$QA_URL"
echo "   - PROD: http://$PROD_URL"
echo ""
echo "✨ Done!"
