# Ultra-Minimal Demo Resource Limits
# Purpose: Absolute minimum resource requests for demo purposes only
# For: Demo/Development environment ONLY (NOT for production or load testing)
#
# Total Resources Available:
# - 4x t3.large nodes = 8 vCPU, ~28 GB RAM total
# - Current usage: Only 3-5% CPU, 15-19% memory per node
# - Plenty of headroom for ultra-minimal settings
#
# Strategy: Ultra-low CPU (10-25m), minimal memory (32Mi)
# Note: LimitRange will be adjusted to allow 32Mi minimum
#
# Previous Total: 600m CPU, ~1GB RAM
# New Total:      ~200m CPU, ~400MB RAM (70% reduction)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 25m        # Ultra-minimal for demo
            memory: 32Mi    # Absolute minimum
          limits:
            cpu: 100m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 20m        # Ultra-minimal for demo
            memory: 32Mi    # Absolute minimum
          limits:
            cpu: 100m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 15m        # Ultra-minimal for demo
            memory: 32Mi    # Absolute minimum
          limits:
            cpu: 100m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 15m        # Ultra-minimal for demo
            memory: 32Mi    # Absolute minimum
          limits:
            cpu: 100m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 15m        # Ultra-minimal for demo
            memory: 32Mi    # Absolute minimum
          limits:
            cpu: 100m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 15m        # Ultra-minimal for demo
            memory: 32Mi    # Absolute minimum
          limits:
            cpu: 100m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 15m        # Ultra-minimal for demo
            memory: 32Mi    # Absolute minimum
          limits:
            cpu: 100m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 15m        # Ultra-minimal for demo
            memory: 32Mi    # Absolute minimum
          limits:
            cpu: 100m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 20m        # Ultra-minimal for demo (Python needs slightly more)
            memory: 48Mi    # Python service needs a bit more
          limits:
            cpu: 150m
            memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 25m        # Ultra-minimal for demo (Java needs slightly more)
            memory: 48Mi    # Java service needs a bit more
          limits:
            cpu: 150m
            memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 10m        # Ultra-minimal for demo (Redis is very efficient)
            memory: 32Mi    # Redis can run on very little
          limits:
            cpu: 100m
            memory: 128Mi
