# Copyright 2024
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resource-quota
spec:
  hard:
    requests.cpu: "15"
    requests.memory: 20Gi
    limits.cpu: "30"
    limits.memory: 40Gi
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
spec:
  limits:
  - max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 10m       # Ultra-minimal for demo (was 50m)
      memory: 32Mi   # Ultra-minimal for demo (was 64Mi)
    default:
      cpu: 200m      # Reduced default (was 500m)
      memory: 256Mi  # Reduced default (was 512Mi)
    defaultRequest:
      cpu: 50m       # Reduced default request (was 200m)
      memory: 64Mi   # Reduced default request (was 256Mi)
    type: Container
