---
name: "Auto-Merge Version Bump PRs"

'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    name: "Auto-Merge if Approved"
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == 'github-actions[bot]' ||
      contains(github.event.pull_request.labels.*.name, 'auto-merge')

    steps:
      - name: Check PR Labels
        id: check-labels
        run: |
          # Check if PR has auto-merge label or is from github-actions bot
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'auto-merge') }}" == "true" ]] || \
             [[ "${{ github.event.pull_request.user.login }}" == "github-actions[bot]" ]]; then
            echo "should_merge=true" >> $GITHUB_OUTPUT
            echo "✅ PR eligible for auto-merge"
          else
            echo "should_merge=false" >> $GITHUB_OUTPUT
            echo "⏸️  PR not eligible for auto-merge"
          fi

      - name: Wait for Required Checks
        if: steps.check-labels.outputs.should_merge == 'true'
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'Pipeline Initialization'  # Wait for master pipeline init
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped,neutral

      - name: Enable Auto-Merge
        if: steps.check-labels.outputs.should_merge == 'true'
        run: |
          gh pr merge "${{ github.event.pull_request.number }}" \
            --auto \
            --merge \
            --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: Summary
        if: steps.check-labels.outputs.should_merge == 'true'
        run: |
          echo "## ✅ Auto-Merge Enabled" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "PR #${{ github.event.pull_request.number }} will be automatically merged when:" >> $GITHUB_STEP_SUMMARY
          echo "- All required checks pass" >> $GITHUB_STEP_SUMMARY
          echo "- No conflicts exist" >> $GITHUB_STEP_SUMMARY
          echo "- Branch is up to date" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Title**: ${{ github.event.pull_request.title }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch**: \`${{ github.event.pull_request.head.ref }}\`" >> $GITHUB_STEP_SUMMARY
