name: Deploy with ServiceNow DevOps Change

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

env:
  AWS_REGION: eu-west-2
  CLUSTER_NAME: microservices
  SERVICENOW_INSTANCE_URL: ${{ secrets.SERVICENOW_INSTANCE_URL }}

jobs:
  # Job 1: Create ServiceNow Change Request using DevOps Change Action
  create-change-request:
    name: Create Change Request
    runs-on: ubuntu-latest
    outputs:
      change_request_number: ${{ steps.create-change.outputs.change-request-number }}
      change_request_sys_id: ${{ steps.create-change.outputs.change-request-sys-id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Change Request via ServiceNow DevOps Action
        id: create-change
        uses: ServiceNow/servicenow-devops-change@v6.1.0
        with:
          # Authentication (token-based - recommended)
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SERVICENOW_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}  # GitHub Demo tool sys_id: 2fe9c38bc36c72d0e1bbf0cb050131cc

          # GitHub context (required for pipeline tracking)
          context-github: ${{ toJSON(github) }}
          job-name: 'Create Change Request'

          # Change request details (JSON format)
          change-request: |
            {
              "setCloseCode": "true",
              "autoCloseChange": ${{ github.event.inputs.environment == 'dev' }},
              "attributes": {
                "short_description": "Deploy Online Boutique microservices to ${{ github.event.inputs.environment }}",
                "description": "Automated deployment of 11 microservices via GitHub Actions.\n\nApplication: Online Boutique\nEnvironment: ${{ github.event.inputs.environment }}\nCommit: ${{ github.sha }}\nRepository: ${{ github.repository }}\nTriggered by: ${{ github.actor }}\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "implementation_plan": "1. Run security scans\n2. Deploy using Kustomize to namespace: microservices-${{ github.event.inputs.environment }}\n3. Wait for all deployments to become ready\n4. Verify pod health checks\n5. Update ServiceNow with deployment status",
                "backout_plan": "kubectl rollout undo deployment/<service> -n microservices-${{ github.event.inputs.environment }}\nOR\nkubectl delete -k kustomize/overlays/${{ github.event.inputs.environment }}",
                "test_plan": "1. Check all pods status: kubectl get pods -n microservices-${{ github.event.inputs.environment }}\n2. Verify service endpoints are accessible\n3. Run health checks on all services\n4. Monitor Istio metrics and logs",
                "type": "normal",
                "assignment_group": "Change Management"
              }
            }

          # Polling settings (check approval status)
          interval: '30'      # Check every 30 seconds
          timeout: '3600'     # 1 hour timeout (can increase for prod)

      - name: Change Request Created
        run: |
          CHANGE_NUMBER="${{ steps.create-change.outputs.change-request-number }}"
          CHANGE_SYS_ID="${{ steps.create-change.outputs.change-request-sys-id }}"

          if [ -z "$CHANGE_NUMBER" ] || [ "$CHANGE_NUMBER" == "" ]; then
            echo "❌ ERROR: Change request number not returned from create-change action" >> $GITHUB_STEP_SUMMARY
            echo "This means the ServiceNow DevOps Change API call failed." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Possible causes**:" >> $GITHUB_STEP_SUMMARY
            echo "1. Token authentication failed" >> $GITHUB_STEP_SUMMARY
            echo "2. Tool ID incorrect" >> $GITHUB_STEP_SUMMARY
            echo "3. ServiceNow API error" >> $GITHUB_STEP_SUMMARY
            echo "4. Change Control API not configured" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

          echo "✅ Change Request Created via DevOps Change API" >> $GITHUB_STEP_SUMMARY
          echo "**Number**: $CHANGE_NUMBER" >> $GITHUB_STEP_SUMMARY
          echo "**Sys ID**: $CHANGE_SYS_ID" >> $GITHUB_STEP_SUMMARY
          echo "**View in ServiceNow**: ${{ secrets.SERVICENOW_INSTANCE_URL }}/nav_to.do?uri=change_request.do?sys_id=$CHANGE_SYS_ID" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**DevOps Workspace**: ${{ secrets.SERVICENOW_INSTANCE_URL }}/now/devops-change/home" >> $GITHUB_STEP_SUMMARY

  # Job 2: Pre-Deployment Checks (runs after change is approved)
  pre-deployment-checks:
    name: Pre-Deployment Checks
    runs-on: ubuntu-latest
    needs: create-change-request

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify EKS cluster access
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
          kubectl cluster-info
          kubectl get nodes

      - name: Check namespace exists
        run: |
          NAMESPACE="microservices-${{ github.event.inputs.environment }}"
          if ! kubectl get namespace $NAMESPACE 2>/dev/null; then
            echo "⚠️ Namespace $NAMESPACE does not exist, creating..."
            kubectl create namespace $NAMESPACE
            kubectl label namespace $NAMESPACE istio-injection=enabled
            echo "✅ Namespace created and labeled for Istio injection"
          else
            echo "✅ Namespace $NAMESPACE exists"
          fi

      - name: Pre-deployment validation complete
        run: |
          echo "✅ All pre-deployment checks passed" >> $GITHUB_STEP_SUMMARY
          echo "Ready to deploy to **${{ github.event.inputs.environment }}**" >> $GITHUB_STEP_SUMMARY

  # Job 3: Deploy Application
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    needs: [create-change-request, pre-deployment-checks]
    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy using Kustomize
        id: deploy
        run: |
          ENV="${{ github.event.inputs.environment }}"
          echo "Deploying to environment: $ENV"

          kubectl apply -k kustomize/overlays/$ENV

          echo "NAMESPACE=microservices-$ENV" >> $GITHUB_ENV

      - name: Wait for deployments to be ready
        run: |
          NAMESPACE="${{ env.NAMESPACE }}"
          echo "Waiting for deployments in namespace: $NAMESPACE"

          SERVICES="frontend cartservice productcatalogservice currencyservice paymentservice shippingservice emailservice checkoutservice recommendationservice adservice"

          if [ "${{ github.event.inputs.environment }}" != "prod" ]; then
            SERVICES="$SERVICES loadgenerator"
          fi

          for service in $SERVICES; do
            echo "Waiting for $service..."
            kubectl rollout status deployment/$service -n $NAMESPACE --timeout=5m || echo "⚠️ $service rollout timed out"
          done

      - name: Verify deployment health
        id: health-check
        run: |
          NAMESPACE="${{ env.NAMESPACE }}"

          echo "## Deployment Health Check" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          kubectl get pods -n $NAMESPACE

          RUNNING_PODS=$(kubectl get pods -n $NAMESPACE -o json | jq '[.items[] | select(.status.phase=="Running")] | length')
          TOTAL_PODS=$(kubectl get pods -n $NAMESPACE -o json | jq '.items | length')

          echo "**Running pods**: $RUNNING_PODS / $TOTAL_PODS" >> $GITHUB_STEP_SUMMARY

          if [ $RUNNING_PODS -lt $TOTAL_PODS ]; then
            echo "⚠️ Not all pods are running" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ All pods are running" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Update ServiceNow Change Request - Success
        if: success() && needs.create-change-request.outputs.change_request_number != ''
        uses: ServiceNow/servicenow-devops-update-change@v5.1.0
        with:
          # Authentication (token-based)
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SERVICENOW_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          change-request-number: ${{ needs.create-change-request.outputs.change_request_number }}
          change-request-details: |
            {
              "close_code": "successful",
              "close_notes": "Deployment completed successfully to ${{ github.event.inputs.environment }}.\n\nAll pods running.\nCommit: ${{ github.sha }}\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "state": "3"
            }

      - name: Update ServiceNow via REST API - Success (Fallback)
        if: success() && needs.create-change-request.outputs.change_request_number == ''
        run: |
          echo "⚠️ Change number not available from DevOps API, skipping update" >> $GITHUB_STEP_SUMMARY
          echo "Deployment succeeded but change request update failed" >> $GITHUB_STEP_SUMMARY

  # Job 4: Rollback on Failure
  rollback:
    name: Rollback Deployment
    runs-on: ubuntu-latest
    needs: [create-change-request, deploy]
    if: failure() && needs.deploy.result == 'failure'

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Rollback deployments
        run: |
          ENV="${{ github.event.inputs.environment }}"
          NAMESPACE="microservices-$ENV"

          echo "⚠️ Deployment failed. Rolling back..." >> $GITHUB_STEP_SUMMARY

          SERVICES="frontend cartservice productcatalogservice currencyservice paymentservice shippingservice emailservice checkoutservice recommendationservice adservice"

          for service in $SERVICES; do
            echo "Rolling back $service..."
            kubectl rollout undo deployment/$service -n $NAMESPACE || echo "⚠️ Failed to rollback $service"
          done

          echo "✅ Rollback completed" >> $GITHUB_STEP_SUMMARY

      - name: Update ServiceNow Change Request - Failed
        uses: ServiceNow/servicenow-devops-update-change@v5.1.0
        with:
          # Authentication (token-based)
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SERVICENOW_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          change-request-number: ${{ needs.create-change-request.outputs.change_request_number }}
          change-request-details: |
            {
              "close_code": "unsuccessful",
              "close_notes": "Deployment failed to ${{ github.event.inputs.environment }}. Automatic rollback executed.\n\nLogs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "state": "4"
            }
