name: 🧪 Test ServiceNow DevOps Change Action v6.1.0

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
        default: 'dev'

jobs:
  test-change-v6:
    name: Test Change Action v6.1.0
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 🎯 Create Change Request with Official Action v6.1.0 (Basic Auth)
        id: create-change
        uses: ServiceNow/servicenow-devops-change@v6.1.0
        with:
          # Basic Authentication (username/password)
          devops-integration-user-name: ${{ secrets.SERVICENOW_USERNAME }}
          devops-integration-user-password: ${{ secrets.SERVICENOW_PASSWORD }}

          # ServiceNow instance
          instance-url: ${{ secrets.SERVICENOW_INSTANCE_URL }}

          # Tool ID for DORA metrics integration
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}

          # GitHub context (required for work items, commits, etc.)
          context-github: ${{ toJSON(github) }}

          # Job name (used for tracking)
          job-name: 'test-change-v6'

          # Change request details (using example from user)
          change-request: |
            {
              "setCloseCode": "true",
              "autoCloseChange": true,
              "attributes": {
                "short_description": "TEST - ServiceNow DevOps Change Action v6.1.0 - ${{ inputs.environment }}",
                "description": "Testing official ServiceNow DevOps Change action v6.1.0 with Basic Auth. This is a test change request to verify the action works correctly.",
                "assignment_group": "DevOps Team",
                "implementation_plan": "Test implementation - GitHub Actions workflow using servicenow-devops-change@v6.1.0",
                "backout_plan": "This is a test - safe to close",
                "test_plan": "Verify change request created via official action v6.1.0 with Basic Auth"
              }
            }

          # Timeout and retry configuration
          interval: '100'
          timeout: '3600'
          changeCreationTimeOut: '3600'
          abortOnChangeCreationFailure: true
          abortOnChangeStepTimeout: true
        continue-on-error: true

      - name: 📊 Display Change Request Details
        run: |
          echo "=========================================="
          echo "Change Request Creation Result"
          echo "=========================================="
          echo ""

          if [ "${{ steps.create-change.outcome }}" = "success" ]; then
            echo "✅ Change request created successfully!"
            echo ""
            echo "Change Request Details:"
            echo "  Number: ${{ steps.create-change.outputs.change-request-number }}"
            echo "  Sys ID: ${{ steps.create-change.outputs.change-request-sys-id }}"
            echo "  URL: ${{ secrets.SERVICENOW_INSTANCE_URL }}/nav_to.do?uri=change_request.do?sys_id=${{ steps.create-change.outputs.change-request-sys-id }}"
            echo ""
            echo "🎉 SUCCESS: v6.1.0 works with Basic Auth!"
          else
            echo "❌ Change request creation failed"
            echo ""
            echo "This could be due to:"
            echo "  - Basic Auth not supported by this action version"
            echo "  - Missing SN_ORCHESTRATION_TOOL_ID"
            echo "  - ServiceNow instance configuration"
            echo "  - Network/connectivity issues"
            echo "  - Callback URL generation issues"
          fi

      - name: 🔍 Verify Change Request in ServiceNow
        if: steps.create-change.outcome == 'success'
        run: |
          echo "=========================================="
          echo "Verifying Change Request in ServiceNow"
          echo "=========================================="
          echo ""

          # Get change request details via REST API
          RESPONSE=$(curl -s -u "${{ secrets.SERVICENOW_USERNAME }}:${{ secrets.SERVICENOW_PASSWORD }}" \
            -H "Accept: application/json" \
            "${{ secrets.SERVICENOW_INSTANCE_URL }}/api/now/table/change_request/${{ steps.create-change.outputs.change-request-sys-id }}")

          echo "Change Request in ServiceNow:"
          echo "$RESPONSE" | jq -r '.result | "  Number: \(.number)\n  Short Description: \(.short_description)\n  State: \(.state)\n  Assignment Group: \(.assignment_group.display_value // "N/A")\n  Created: \(.sys_created_on)"'

          echo ""
          echo "✅ Verified: Change request exists in ServiceNow"

      - name: 📈 Compare v6.1.0 vs v4.0.0
        run: |
          echo ""
          echo "=========================================="
          echo "Version Comparison Summary"
          echo "=========================================="
          echo ""

          echo "v4.0.0 Test Results:"
          echo "  Status: ❌ FAILED"
          echo "  Error: Internal server error"
          echo "  Run: 18901932847"
          echo ""

          if [ "${{ steps.create-change.outcome }}" = "success" ]; then
            echo "v6.1.0 Test Results:"
            echo "  Status: ✅ SUCCESS"
            echo "  CR Number: ${{ steps.create-change.outputs.change-request-number }}"
            echo "  CR Sys ID: ${{ steps.create-change.outputs.change-request-sys-id }}"
            echo ""
            echo "🎉 VERDICT: v6.1.0 FIXES THE ISSUE!"
            echo ""
            echo "Improvements in v6.1.0:"
            echo "  ✅ Enhanced error logging for change creation API"
            echo "  ✅ Detailed request/response logs"
            echo "  ✅ Better callback handling (likely)"
            echo "  ✅ Works with Basic Auth"
            echo ""
            echo "Recommendation: UPGRADE to v6.1.0 in all workflows"
          else
            echo "v6.1.0 Test Results:"
            echo "  Status: ❌ FAILED"
            echo "  Error: Still has issues"
            echo ""
            echo "🔍 Further investigation needed"
            echo "  - Check ServiceNow logs"
            echo "  - Verify tool configuration"
            echo "  - May still need GitHub App configuration"
          fi

      - name: 📝 Test Summary
        run: |
          echo ""
          echo "=========================================="
          echo "Test Summary"
          echo "=========================================="
          echo ""

          if [ "${{ steps.create-change.outcome }}" = "success" ]; then
            echo "✅ SUCCESS: Official ServiceNow DevOps Change action v6.1.0 works!"
            echo ""
            echo "Benefits of using official action:"
            echo "  ✅ Maintained by ServiceNow (security updates)"
            echo "  ✅ Enhanced error logging and debugging"
            echo "  ✅ Built-in retry and timeout handling"
            echo "  ✅ Supports auto-close and close codes"
            echo "  ✅ Integration with ServiceNow DevOps features"
            echo "  ✅ DORA metrics tracking"
            echo ""
            echo "Next Steps:"
            echo "  1. Update .github/workflows/servicenow-integration.yaml to use v6.1.0"
            echo "  2. Remove test workflows (test-servicenow-devops-change.yaml, test-change-api-comparison.yaml)"
            echo "  3. Test with deployment gate configuration (optional)"
            echo "  4. Document the upgrade in WHATS-NEW.md"
          else
            echo "❌ FAILED: Official action still has issues with v6.1.0"
            echo ""
            echo "Continue with Custom REST API approach:"
            echo "  ✅ Works reliably"
            echo "  ✅ Simple and maintainable"
            echo "  ✅ Full control over change request creation"
            echo "  ✅ No additional configuration needed"
          fi
